FROM jadlakkis/tmnf-docker-base:latest

USER root

RUN chmod 755 /root && chown root:root /root

RUN mkdir -p /tmp/.X11-unix && chmod 1777 /tmp/.X11-unix

RUN apt-get update && apt-get install -y openssh-server \
    && rm -rf /var/lib/apt/lists/* \
    && mkdir -p /var/run/sshd

EXPOSE 22

CMD ["bash", "-c", "mkdir -p /root/.ssh && echo \"$PUBLIC_KEY\" >> /root/.ssh/authorized_keys && chmod 700 /root/.ssh && chmod 600 /root/.ssh/authorized_keys && service ssh start && sleep infinity"]
